### ISSUE TITLE
Properly include `seg_code` folder in the output

### ISSUE THREAD

**Issue by Connor-Bowley** [MathieuLeclercq/SlicerJawSegmentation#11]
There is nothing in any of the CMake to actually bring the seg_code folder into Slicer. Thus, when I try to run I get 

![image](https://user-images.githubusercontent.com/14840636/175539360-55510c9a-95a2-41ee-b03b-42796d8d15a3.png)

When the extension is actually being installed into / built into Slicer, the source repo won't be there. I don't know exactly how you were adding the extension to slicer, via the Extension Wizard or what, but I think it allowed your `sys.path` shenanigans to work.

When actually installed closer to how it would be from the extension manager, it can't find the code.

I will fix this and put out PR. There is not a clean slicer way to do this, but we can add some CMake that makes it work.

**Comment by Connor-Bowley** [comment]
Fix is in PR https://github.com/MathieuLeclercq/SlicerJawSegmentation/pull/14

**Comment by MathieuLeclercq** [comment]
Thank you for fixing this issue. I have merged your PR.
