### ISSUE TITLE
Nice to have: Automatically toggle on scalars with "Open output surface"

### ISSUE THREAD

**Issue by Connor-Bowley** [MathieuLeclercq/SlicerJawSegmentation#15]
For an example on how to do this see [here](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#apply-vtk-filter-on-a-model-node).

**Comment by MathieuLeclercq** [comment]
Thank you, I've added the feature. However, I would like to set _Viridis_ as the default color table, but [apparently, it is not available](https://apidocs.slicer.org/v4.8/classvtkMRMLColorTableNode.html). Do you know if there is a way to use it?

**Comment by MathieuLeclercq** [comment]
I have added the feature, thank you.
