### ISSUE TITLE
Create tutorial

### ISSUE THREAD

**Issue by Connor-Bowley** [MathieuLeclercq/SlicerJawSegmentation#18]
As part of SlicerSALT, create a google slides tutorial for using the module. As examples, see the following:

SRep: https://bit.ly/3sTEG3H
Groups: https://bit.ly/2WsFiun
SPHARM-PD Generator: https://bit.ly/2Fyn97v

For the install from extension manager slides, use the SRep as basis, since it is up to date with the newer Slicer look.

For now, focus on getting the content of the tutorial (words, screenshots, etc). @bpaniagua will work on getting a google slides template.

**Comment by MathieuLeclercq** [comment]
Hello, 
 [Here is the google slides tutorial.](https://docs.google.com/presentation/d/13VXvELkOLZZUpSX2X78YN-4rVoMK5y7nmpZnVi2fAHg/edit?usp=sharing)
As you've asked, I have mainly focused on the text and screenshots.
It is a bit short but the module is quite straightforward.

I am open to any suggestions.

**Comment by Connor-Bowley** [comment]
I have left some suggestions as comments in the slides. Overall, looking good.
