### ISSUE TITLE
Module name specificity

### ISSUE THREAD

**Issue by Connor-Bowley** [MathieuLeclercq/SlicerJawSegmentation#3]
It is my opinion that "prediction" is too generic of a module name to have in an extension. The module name should likely relate to the extension name.

**Comment by MathieuLeclercq** [comment]
I changed the name to "Crown segmentation - FiboSeg"

**Comment by Connor-Bowley** [comment]
It would be preferable to change the whole module names (i.e. the names of the classes and folders), not just the display name. Reason being the module will be able to be accessed via `slicer.modules.prediction` and `from prediction import predictionLogic`, which is both too generic and not really associated with the module name.

**Comment by MathieuLeclercq** [comment]
I've changed the whole module names accordingly. Thanks

**Comment by Connor-Bowley** [comment]
Looks good. Thanks.
