### ISSUE TITLE
Remove default test

### ISSUE THREAD

**Issue by Connor-Bowley** [MathieuLeclercq/SlicerJawSegmentation#4]
If you aren't going to write tests for the prediction module, then remove the test that comes by default with the extension wizard, so it doesn't fail.
https://github.com/MathieuLeclercq/SlicerJawSegmentation/blob/e6cfcd3fad261feecc65b6a01d939213960a3e3f/prediction/prediction.py#L544-L594

**Comment by MathieuLeclercq** [comment]
Thank you, I'm going to remove the default test for now.

**Comment by Connor-Bowley** [comment]
Thanks
