### ISSUE TITLE
Remove hardcoded path on your machine

### ISSUE THREAD

**Issue by Connor-Bowley** [MathieuLeclercq/SlicerJawSegmentation#9]
This should not be hardcoded to your machine. Likely it should be blank to start.

https://github.com/MathieuLeclercq/SlicerJawSegmentation/blob/8411a7fdc91757fa87010c5312d31a5440bc391d/CrownSegmentation/Resources/UI/CrownSegmentation.ui#L208

**Comment by MathieuLeclercq** [comment]
Fixed. Thank you.
